// Genshin Optimizer — UI layer (vanilla DOM, re-renders each tab wholesale).
let currentTab = 'characters';
let charSearchQuery = '';
let charElementFilter = 'All';
let weaponTypeFilter = 'All';
let lastWeaponAssignmentResult = null;

// Placeholder icons only (no official game art — see notes elsewhere on why).
const ELEMENT_ICON = { Pyro: '🔥', Hydro: '💧', Electro: '⚡', Cryo: '❄️', Anemo: '🌪️', Geo: '🪨', Dendro: '🌿' };
const WEAPON_TYPE_ICON = { Sword: '🗡️', Claymore: '⚔️', Polearm: '🔱', Bow: '🏹', Catalyst: '📖' };
const SLOT_ICON = { flower: '🌸', plume: '🪶', sands: '⏳', goblet: '🏆', circlet: '👑' };

function initials(name) {
  const words = String(name).replace(/\(.*?\)/g, '').trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return '?';
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return (words[0][0] + words[words.length - 1][0]).toUpperCase();
}

// Real character face art from EnkaNetwork's public UI asset CDN (enka.network/ui/*),
// which they host specifically for third-party community tools. Falls back to the
// colored-initials placeholder if there's no mapped icon or the image fails to load.
function avatarHtml(character, sizeClass) {
  const cls = 'char-avatar avatar-' + character.element.toLowerCase() + (sizeClass ? ' ' + sizeClass : '');
  const fallbackSpan = `<span class="${cls}">${initials(character.name)}</span>`;
  const key = GENSHIN_DATA.characterIcons[character.id];
  if (!key) return fallbackSpan;
  const url = `https://enka.network/ui/UI_AvatarIcon_${key}.png`;
  const onerror = `this.outerHTML='${fallbackSpan.replace(/'/g, "&#39;").replace(/"/g, '&quot;')}'`;
  return `<img src="${url}" alt="${escapeHtml(character.name)}" class="${cls} char-avatar-img" onerror="${onerror}">`;
}

// Real weapon icon from the same CDN, falling back to the emoji weapon-type glyph.
function weaponIconHtml(weaponInstance) {
  const emoji = WEAPON_TYPE_ICON[weaponInstance.type] || '';
  const def = weaponInstance.weaponId ? GENSHIN_DATA.weapons.find((w) => w.id === weaponInstance.weaponId) : null;
  if (!def || !def.icon) return `<span class="icon-tag">${emoji}</span>`;
  const url = `https://enka.network/ui/${def.icon}.png`;
  const onerror = `this.outerHTML='<span class=&quot;icon-tag&quot;>${emoji}</span>'`;
  return `<img src="${url}" alt="" class="weapon-icon" onerror="${onerror}">`;
}

function isPreferredWeapon(characterId, weaponId) {
  const list = GENSHIN_DATA.preferredWeapons && GENSHIN_DATA.preferredWeapons[characterId];
  return !!(list && weaponId && list.includes(weaponId));
}

// --- Third-party roster import (e.g. a character list generated by another AI chat) ---
const NAME_ALIASES = { itto: 'aratakiitto', heizou: 'shikanoinheizou' };

function normalizeName(str) {
  return String(str).toLowerCase().replace(/\(.*?\)/g, '').replace(/[^a-z0-9]/g, '').trim();
}

function findCharacterByName(name) {
  let norm = normalizeName(name);
  if (NAME_ALIASES[norm]) norm = NAME_ALIASES[norm];
  return Store.allCharacters().find((c) => normalizeName(c.name) === norm) || null;
}

function looksLikeGeminiRoster(parsed) {
  return !!(parsed && typeof parsed === 'object' && parsed.characters &&
    (Array.isArray(parsed.characters.five_star) || Array.isArray(parsed.characters.four_star)));
}

function importGeminiRoster(parsed) {
  const entries = [];
  const skipped = [];
  const specialUnits = (parsed.account_overview && parsed.account_overview.special_units) || [];
  specialUnits.forEach((u) => {
    if (u.source) { skipped.push(`${u.name} (event/collab unit from ${u.source}, not a standard roster addition)`); return; }
    entries.push({ name: u.name, constellation: null, level: u.level != null ? u.level : null });
  });
  const fiveStar = parsed.characters.five_star || [];
  const fourStar = parsed.characters.four_star || [];
  fiveStar.concat(fourStar).forEach((c) => {
    entries.push({ name: c.name, constellation: c.constellation || null, level: c.level != null ? c.level : null });
  });

  const matched = [];
  const unmatched = [];
  entries.forEach((e) => {
    const character = findCharacterByName(e.name);
    if (character) {
      Store.setOwned(character.id, true);
      Store.setRosterMeta(character.id, { constellation: e.constellation, level: e.level });
      matched.push(character.name);
    } else {
      unmatched.push(e.name);
    }
  });
  return { matched, unmatched, skipped };
}

// --- Third-party weapon inventory import ---
function looksLikeGeminiWeaponInventory(parsed) {
  return !!(parsed && typeof parsed === 'object' && parsed.weapons && !Array.isArray(parsed.weapons) &&
    (Array.isArray(parsed.weapons.five_star) || (parsed.weapons.four_star_and_three_star && typeof parsed.weapons.four_star_and_three_star === 'object')));
}

function parseRefinement(r) {
  const m = String(r).match(/\d+/);
  return m ? Number(m[0]) : 1;
}

function parseLevel(l) {
  if (l == null) return null;
  const m = String(l).match(/\d+/);
  return m ? Number(m[0]) : null;
}

function findWeaponByName(name) {
  const norm = normalizeName(name);
  return GENSHIN_DATA.weapons.find((w) => normalizeName(w.name) === norm) || null;
}

function importGeminiWeapons(parsed) {
  const rawEntries = (parsed.weapons.five_star || []).slice();
  const grouped = parsed.weapons.four_star_and_three_star || {};
  Object.keys(grouped).forEach((cat) => rawEntries.push(...(grouped[cat] || [])));

  const matched = [];
  const unmatched = [];
  rawEntries.forEach((w) => {
    const def = findWeaponByName(w.name);
    if (!def) { unmatched.push(w.name); return; }
    const refinement = parseRefinement(w.refinement);
    const assignedName = w.assigned_to;
    let assignedTo = null;
    if (assignedName && typeof assignedName === 'string' && !/unassigned/i.test(assignedName) && !assignedName.includes('/')) {
      const char = findCharacterByName(assignedName);
      if (char) assignedTo = char.id;
    }
    const copies = w.copies || 1;
    for (let i = 0; i < copies; i++) {
      const weapon = Store.addWeapon({
        weaponId: def.id,
        name: def.name,
        type: def.type,
        refinement,
        baseAtk: def.baseAtk,
        subStat: def.subStat,
        subStatValue: def.subStatValue,
      });
      if (i === 0 && assignedTo) { weapon.assignedTo = assignedTo; Store.save(); }
    }
    matched.push(def.name);
  });
  return { matched, unmatched };
}

document.addEventListener('DOMContentLoaded', init);

function init() {
  Store.load();
  if (!Store.testPersistence()) {
    const banner = document.createElement('div');
    banner.className = 'persistence-warning';
    banner.textContent = "⚠ This browser/window isn't saving data between reloads (likely private/incognito mode, or a \"clear data on close\" setting). Anything you enter here will be lost when you close this tab — use Export before closing, or reopen this page in a normal browser window.";
    document.body.insertBefore(banner, document.body.firstChild);
  }
  document.querySelectorAll('.tab-btn').forEach((btn) => {
    btn.addEventListener('click', () => switchTab(btn.dataset.tab));
  });
  document.getElementById('export-btn').addEventListener('click', doExport);
  document.getElementById('import-input').addEventListener('change', doImport);
  document.getElementById('reset-btn').addEventListener('click', doReset);
  initCloudSyncUi();
  switchTab('characters');
}

function initCloudSyncUi() {
  const panel = document.getElementById('cloud-sync-panel');
  const statusEl = document.getElementById('cloud-sync-status');
  const setStatus = (msg, isError) => {
    statusEl.textContent = msg;
    statusEl.style.color = isError ? 'var(--danger)' : '';
  };

  document.getElementById('cloud-sync-btn').addEventListener('click', () => {
    panel.hidden = !panel.hidden;
    if (!panel.hidden) setStatus(CloudSync.getPat() ? 'Token saved on this device.' : 'No token saved on this device yet.');
  });

  document.getElementById('cloud-pat-save-btn').addEventListener('click', () => {
    const input = document.getElementById('cloud-pat-input');
    const pat = input.value.trim();
    if (!pat) { setStatus('Enter a token first.', true); return; }
    CloudSync.setPat(pat);
    input.value = '';
    setStatus('Token saved on this device.');
  });

  document.getElementById('cloud-push-btn').addEventListener('click', async () => {
    setStatus('Pushing…');
    try {
      await CloudSync.push();
      setStatus('Pushed. This device\'s data is now the cloud copy — pull it on your other device(s).');
    } catch (err) {
      setStatus(err.message, true);
    }
  });

  document.getElementById('cloud-pull-btn').addEventListener('click', async () => {
    if (!confirm('This replaces everything currently saved on this device with the cloud copy. Continue?')) return;
    setStatus('Pulling…');
    try {
      const content = await CloudSync.pull();
      Store.importJson(content);
      lastWeaponAssignmentResult = null;
      renderTab();
      setStatus('Pulled cloud data into this device.');
    } catch (err) {
      setStatus(err.message, true);
    }
  });
}

function switchTab(tab) {
  currentTab = tab;
  document.querySelectorAll('.tab-btn').forEach((btn) => btn.classList.toggle('active', btn.dataset.tab === tab));
  renderTab();
}

function renderTab() {
  const app = document.getElementById('app');
  if (currentTab === 'characters') renderCharactersTab(app);
  else if (currentTab === 'weapons') renderWeaponsTab(app);
  else if (currentTab === 'artifacts') renderArtifactsTab(app);
  else if (currentTab === 'weaponOptimizer') renderWeaponOptimizerTab(app);
  else if (currentTab === 'artifactOptimizer') renderArtifactOptimizerTab(app);
}

function escapeHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function doExport() {
  const blob = new Blob([Store.exportJson()], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'genshin-optimizer-data.json';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function doImport(e) {
  const file = e.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    let parsed;
    try {
      parsed = JSON.parse(reader.result);
    } catch (err) {
      alert('Import failed: file is not valid JSON.');
      return;
    }
    try {
      if (looksLikeGeminiRoster(parsed)) {
        const { matched, unmatched, skipped } = importGeminiRoster(parsed);
        lastWeaponAssignmentResult = null;
        switchTab('characters');
        const total = matched.length + unmatched.length + skipped.length;
        let msg = `Found ${total} entries in the file. Imported ${matched.length} as owned characters.`;
        if (unmatched.length) msg += `\n\nCouldn't match ${unmatched.length} (not in my built-in list): ${unmatched.join(', ')}. Add these via "Add a custom character" if you want them tracked.`;
        if (skipped.length) msg += `\n\nSkipped ${skipped.length}: ${skipped.join(', ')}.`;
        alert(msg);
      } else if (looksLikeGeminiWeaponInventory(parsed)) {
        const { matched, unmatched } = importGeminiWeapons(parsed);
        lastWeaponAssignmentResult = null;
        switchTab('weapons');
        let msg = `Imported ${matched.length} weapon(s) into your inventory.`;
        if (unmatched.length) msg += `\n\nCouldn't match ${unmatched.length} (not in my built-in weapon list): ${unmatched.join(', ')}. Add these manually via "Custom weapon" in the Weapons tab if you want them tracked.`;
        alert(msg);
      } else if (parsed && (Array.isArray(parsed.weapons) || Array.isArray(parsed.artifacts) || Array.isArray(parsed.customCharacters) || (parsed.roster && typeof parsed.roster === 'object' && !Array.isArray(parsed.roster)))) {
        Store.importJson(reader.result);
        const s = Store.state;
        const ownedCount = Object.values(s.roster).filter((r) => r.owned).length;
        lastWeaponAssignmentResult = null;
        switchTab('characters');
        alert(`Data imported: ${ownedCount} owned character(s), ${s.weapons.length} weapon(s), ${s.artifacts.length} artifact(s).`);
      } else {
        alert("This JSON doesn't match a format I recognize (neither this app's export, nor a roster/weapon file I know how to read).");
      }
    } catch (err) {
      console.error('Import failed:', err);
      alert('Import failed: ' + err.message);
    }
  };
  reader.readAsText(file);
  e.target.value = '';
}

function doReset() {
  if (confirm('This clears all your saved characters, weapons, and artifacts. Continue?')) {
    Store.reset();
    lastWeaponAssignmentResult = null;
    renderTab();
  }
}

// ---------------------------------------------------------------- Characters
function renderCharactersTab(app) {
  app.innerHTML = `
    <section class="panel">
      <h2>My Roster</h2>
      <p class="hint">Check the characters you own. Owned characters get stat-priority sliders (0 = irrelevant, 3 = core stat) used by both optimizers, and can pick target artifact sets.</p>
      <input type="text" id="char-search" placeholder="Search characters..." value="${escapeHtml(charSearchQuery)}">
      <div id="char-filter-tabs" class="subtabs"></div>
      <div id="char-list" class="char-list"></div>
      <details class="add-custom">
        <summary>+ Add a custom character (not in the built-in list)</summary>
        <form id="add-char-form" class="inline-form">
          <label>Name<input type="text" id="new-char-name" placeholder="Name" required></label>
          <label>Element
            <select id="new-char-element">
              <option>Pyro</option><option>Hydro</option><option>Electro</option><option>Cryo</option>
              <option>Anemo</option><option>Geo</option><option>Dendro</option>
            </select>
          </label>
          <label>Weapon
            <select id="new-char-weapon">${GENSHIN_DATA.weaponTypes.map((t) => `<option>${t}</option>`).join('')}</select>
          </label>
          <button type="submit">Add</button>
        </form>
      </details>
    </section>
  `;

  document.getElementById('char-search').addEventListener('input', (e) => {
    charSearchQuery = e.target.value;
    renderCharList();
  });

  document.getElementById('add-char-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const name = document.getElementById('new-char-name').value.trim();
    if (!name) return;
    const element = document.getElementById('new-char-element').value;
    const weaponType = document.getElementById('new-char-weapon').value;
    const id = 'custom_' + name.toLowerCase().replace(/[^a-z0-9]+/g, '_') + '_' + Date.now();
    Store.addCustomCharacter({ id, name, element, weaponType, rarity: 5, statPriority: {} });
    Store.setOwned(id, true);
    renderCharactersTab(app);
  });

  renderCharFilterTabs();
  renderCharList();
}

const ELEMENT_ORDER = ['Pyro', 'Hydro', 'Electro', 'Cryo', 'Anemo', 'Geo', 'Dendro'];

function renderCharFilterTabs() {
  const container = document.getElementById('char-filter-tabs');
  if (!container) return;
  const all = Store.allCharacters();
  const knownElements = new Set(ELEMENT_ORDER);
  const present = ELEMENT_ORDER.filter((el) => all.some((c) => c.element === el));
  const hasOther = all.some((c) => !knownElements.has(c.element));
  const tabs = ['All', ...present, ...(hasOther ? ['Other'] : [])];
  container.innerHTML = tabs.map((t) =>
    `<button class="subtab-btn ${charElementFilter === t ? 'active' : ''}" data-element="${t}">${t === 'All' ? 'All' : (ELEMENT_ICON[t] || '') + ' ' + t}</button>`
  ).join('');
  container.querySelectorAll('.subtab-btn').forEach((btn) => {
    btn.addEventListener('click', () => {
      charElementFilter = btn.dataset.element;
      renderCharFilterTabs();
      renderCharList();
    });
  });
}

function renderCharRow(c) {
  const entry = Store.getRosterEntry(c.id);
  return `
    <div class="char-row">
      <label class="char-row-main">
        <input type="checkbox" class="own-check" data-id="${c.id}" ${entry.owned ? 'checked' : ''}>
        ${avatarHtml(c)}
        <span class="char-name">${escapeHtml(c.name)}</span>
        <span class="rarity-stars rarity-${c.rarity}">${'★'.repeat(c.rarity)}</span>
        ${entry.owned && (entry.constellation || entry.level != null) ? `<span class="badge">${escapeHtml([entry.constellation, entry.level != null ? 'Lv ' + entry.level : ''].filter(Boolean).join(' · '))}</span>` : ''}
        <span class="badge badge-${c.element.toLowerCase()}">${ELEMENT_ICON[c.element] || ''} ${c.element}</span>
        <span class="badge">${WEAPON_TYPE_ICON[c.weaponType] || ''} ${c.weaponType}</span>
      </label>
      ${entry.owned ? renderCharDetail(c, entry) : ''}
    </div>
  `;
}

function renderCharList() {
  const container = document.getElementById('char-list');
  if (!container) return;
  const q = charSearchQuery.toLowerCase();
  let filtered = Store.allCharacters().filter((c) => c.name.toLowerCase().includes(q));
  if (charElementFilter !== 'All') {
    const knownElements = new Set(ELEMENT_ORDER);
    filtered = charElementFilter === 'Other'
      ? filtered.filter((c) => !knownElements.has(c.element))
      : filtered.filter((c) => c.element === charElementFilter);
  }

  if (filtered.length === 0) {
    container.innerHTML = '<p class="hint">No characters match.</p>';
    return;
  }

  // Owned characters first, then not-owned (sorted the same way within each bucket).
  const byRarityThenName = (a, b) => (b.rarity - a.rarity) || a.name.localeCompare(b.name);
  const byOwnedThenRarityThenName = (a, b) => {
    const ownedA = Store.getRosterEntry(a.id).owned ? 1 : 0;
    const ownedB = Store.getRosterEntry(b.id).owned ? 1 : 0;
    return ownedB - ownedA || byRarityThenName(a, b);
  };

  const knownElements = new Set(ELEMENT_ORDER);
  const groupElements = charElementFilter === 'All'
    ? [...ELEMENT_ORDER, ...(filtered.some((c) => !knownElements.has(c.element)) ? ['Other'] : [])]
    : [charElementFilter];
  const groups = groupElements.map((element) => ({
    element,
    chars: (element === 'Other' ? filtered.filter((c) => !knownElements.has(c.element)) : filtered.filter((c) => c.element === element))
      .sort(byOwnedThenRarityThenName),
  })).filter((g) => g.chars.length);

  container.innerHTML = groups.map((g) => `
    ${charElementFilter === 'All' ? `<div class="group-header">${ELEMENT_ICON[g.element] || ''} ${g.element}</div>` : ''}
    ${g.chars.map(renderCharRow).join('')}
  `).join('');

  container.querySelectorAll('.own-check').forEach((cb) => {
    cb.addEventListener('change', (e) => {
      Store.setOwned(e.target.dataset.id, e.target.checked);
      renderCharList();
    });
  });
  container.querySelectorAll('.priority-slider').forEach((sl) => {
    sl.addEventListener('input', (e) => {
      const charId = e.target.dataset.charId;
      const stat = e.target.dataset.stat;
      const c = Store.getCharacter(charId);
      const entry = Store.getRosterEntry(charId);
      const base = Object.assign({}, entry.priorityOverride || c.statPriority || {});
      base[stat] = Number(e.target.value);
      Store.setPriorityOverride(charId, base);
      e.target.nextElementSibling.textContent = e.target.value;
    });
  });
  container.querySelectorAll('.target-set-select').forEach((sel) => {
    sel.addEventListener('change', (e) => {
      const charId = e.target.dataset.charId;
      const selected = Array.from(e.target.selectedOptions).map((o) => o.value);
      Store.setTargetSets(charId, selected);
    });
  });
}

function renderCharDetail(c, entry) {
  const weights = entry.priorityOverride || c.statPriority || {};
  const sliders = GENSHIN_DATA.priorityStatKeys.map((stat) => {
    const val = weights[stat] || 0;
    return `
      <div class="slider-row">
        <span class="slider-label">${GENSHIN_DATA.statLabels[stat]}</span>
        <input type="range" min="0" max="3" step="1" value="${val}" class="priority-slider" data-char-id="${c.id}" data-stat="${stat}">
        <span class="slider-value">${val}</span>
      </div>
    `;
  }).join('');
  const setOptions = GENSHIN_DATA.artifactSets.map((s) =>
    `<option value="${s.id}" ${entry.targetSets.includes(s.id) ? 'selected' : ''}>${escapeHtml(s.name)}</option>`
  ).join('');
  return `
    <div class="char-detail">
      <div class="priority-grid">${sliders}</div>
      <label class="target-set-label">Target artifact set(s) — informational only (ctrl/cmd-click for multiple)
        <select multiple size="4" class="target-set-select" data-char-id="${c.id}">${setOptions}</select>
      </label>
    </div>
  `;
}

// ------------------------------------------------------------------ Weapons
function renderWeaponsTab(app) {
  app.innerHTML = `
    <section class="panel">
      <h2>My Weapons</h2>
      <p class="hint">Pick a weapon to prefill its reference stats (Level 90), then adjust if your copy differs.</p>
      <form id="add-weapon-form" class="inline-form">
        <label>Type<select id="wpn-type">${GENSHIN_DATA.weaponTypes.map((t) => `<option value="${t}">${t}</option>`).join('')}</select></label>
        <label>Weapon<select id="wpn-select"></select></label>
        <label id="wpn-custom-name-wrap" style="display:none;">Custom name<input type="text" id="wpn-custom-name" placeholder="Weapon name"></label>
        <label>Refine<select id="wpn-refine">${[1, 2, 3, 4, 5].map((r) => `<option value="${r}">R${r}</option>`).join('')}</select></label>
        <label>Base ATK<input type="number" id="wpn-atk" step="0.1" required></label>
        <label>Substat
          <select id="wpn-substat">${GENSHIN_DATA.substatKeys.concat(['elementalDmg', 'physicalDmg']).map((s) => `<option value="${s}">${GENSHIN_DATA.statLabels[s] || s}</option>`).join('')}</select>
        </label>
        <label>Substat value<input type="number" id="wpn-substat-value" step="0.1"></label>
        <button type="submit">Add weapon</button>
      </form>
      <div id="weapon-filter-tabs" class="subtabs"></div>
      <div id="weapon-list"></div>
    </section>
  `;

  const typeSel = document.getElementById('wpn-type');
  const wpnSel = document.getElementById('wpn-select');
  const customNameWrap = document.getElementById('wpn-custom-name-wrap');
  const customName = document.getElementById('wpn-custom-name');
  const atkInput = document.getElementById('wpn-atk');
  const substatSel = document.getElementById('wpn-substat');
  const substatValInput = document.getElementById('wpn-substat-value');

  function populateWeaponOptions() {
    const type = typeSel.value;
    const list = GENSHIN_DATA.weapons.filter((w) => w.type === type);
    wpnSel.innerHTML = list.map((w) => `<option value="${w.id}">${escapeHtml(w.name)} (${'★'.repeat(w.rarity)})</option>`).join('')
      + `<option value="__custom__">— Custom weapon —</option>`;
    onWeaponPick();
  }

  function onWeaponPick() {
    const val = wpnSel.value;
    if (val === '__custom__') {
      customNameWrap.style.display = '';
      substatSel.disabled = false;
      atkInput.value = '';
      substatValInput.value = '';
    } else {
      customNameWrap.style.display = 'none';
      const w = GENSHIN_DATA.weapons.find((x) => x.id === val);
      if (w) {
        atkInput.value = w.baseAtk;
        substatSel.value = w.subStat;
        substatValInput.value = w.subStatValue;
      }
      substatSel.disabled = true;
    }
  }

  typeSel.addEventListener('change', populateWeaponOptions);
  wpnSel.addEventListener('change', onWeaponPick);
  populateWeaponOptions();

  document.getElementById('add-weapon-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const type = typeSel.value;
    const val = wpnSel.value;
    const name = val === '__custom__'
      ? (customName.value.trim() || 'Custom Weapon')
      : ((GENSHIN_DATA.weapons.find((w) => w.id === val) || {}).name || 'Weapon');
    const weapon = {
      weaponId: val === '__custom__' ? null : val,
      name,
      type,
      refinement: Number(document.getElementById('wpn-refine').value),
      baseAtk: Number(atkInput.value) || 0,
      subStat: substatSel.value,
      subStatValue: Number(substatValInput.value) || 0,
    };
    Store.addWeapon(weapon);
    renderWeaponsTab(app);
  });

  renderWeaponFilterTabs();
  renderWeaponList();
}

function renderWeaponFilterTabs() {
  const container = document.getElementById('weapon-filter-tabs');
  if (!container) return;
  const present = GENSHIN_DATA.weaponTypes.filter((t) => Store.state.weapons.some((w) => w.type === t));
  const tabs = ['All', ...present];
  container.innerHTML = tabs.map((t) =>
    `<button class="subtab-btn ${weaponTypeFilter === t ? 'active' : ''}" data-type="${t}">${t === 'All' ? 'All' : (WEAPON_TYPE_ICON[t] || '') + ' ' + t}</button>`
  ).join('');
  container.querySelectorAll('.subtab-btn').forEach((btn) => {
    btn.addEventListener('click', () => {
      weaponTypeFilter = btn.dataset.type;
      renderWeaponFilterTabs();
      renderWeaponList();
    });
  });
}

function weaponRarity(w) {
  const def = w.weaponId ? GENSHIN_DATA.weapons.find((x) => x.id === w.weaponId) : null;
  return def ? def.rarity : 0;
}

function renderWeaponRow(w) {
  const assignedChar = w.assignedTo ? Store.getCharacter(w.assignedTo) : null;
  const rarity = weaponRarity(w);
  const stars = rarity ? '★'.repeat(rarity) : '';
  return `<tr>
    <td>${weaponIconHtml(w)} ${escapeHtml(w.name)}${stars ? ` <span class="rarity-stars rarity-${rarity}">${stars}</span>` : ''}</td>
    <td>${WEAPON_TYPE_ICON[w.type] || ''} ${w.type}</td>
    <td>R${w.refinement}</td>
    <td>${w.baseAtk}</td>
    <td>${GENSHIN_DATA.statLabels[w.subStat] || w.subStat}: ${w.subStatValue}</td>
    <td>${assignedChar ? `${avatarHtml(assignedChar, 'avatar-sm')} ${escapeHtml(assignedChar.name)}` : '—'}</td>
    <td><button class="danger-btn" data-id="${w.instanceId}">Remove</button></td>
  </tr>`;
}

function renderWeaponList() {
  const container = document.getElementById('weapon-list');
  if (!container) return;
  const weapons = Store.state.weapons;
  if (weapons.length === 0) { container.innerHTML = '<p class="hint">No weapons added yet.</p>'; return; }

  const byRarityThenName = (a, b) => (weaponRarity(b) - weaponRarity(a)) || a.name.localeCompare(b.name);
  const types = weaponTypeFilter === 'All' ? GENSHIN_DATA.weaponTypes : [weaponTypeFilter];
  const groups = types
    .map((type) => ({ type, items: weapons.filter((w) => w.type === type).sort(byRarityThenName) }))
    .filter((g) => g.items.length);

  if (groups.length === 0) { container.innerHTML = '<p class="hint">No weapons of this type yet.</p>'; return; }

  container.innerHTML = groups.map((g) => `
    ${weaponTypeFilter === 'All' ? `<div class="group-header">${WEAPON_TYPE_ICON[g.type] || ''} ${g.type}</div>` : ''}
    <table class="data-table">
      <thead><tr><th>Weapon</th><th>Type</th><th>Refine</th><th>ATK</th><th>Substat</th><th>Assigned to</th><th></th></tr></thead>
      <tbody>${g.items.map(renderWeaponRow).join('')}</tbody>
    </table>
  `).join('');

  container.querySelectorAll('.danger-btn').forEach((btn) => {
    btn.addEventListener('click', () => { Store.removeWeapon(btn.dataset.id); renderWeaponList(); });
  });
}

// ---------------------------------------------------------------- Artifacts
function renderArtifactsTab(app) {
  app.innerHTML = `
    <section class="panel">
      <h2>My Artifacts</h2>
      <p class="hint">Enter your actual rolled substat values for accurate scoring. Reserve a piece for a character in the table below to keep it out of other characters' recommendations.</p>
      <form id="add-artifact-form" class="artifact-form">
        <label>Set<select id="art-set">${GENSHIN_DATA.artifactSets.map((s) => `<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}</select></label>
        <label>Slot<select id="art-slot">${GENSHIN_DATA.artifactSlots.map((s) => `<option value="${s.id}">${SLOT_ICON[s.id] || ''} ${s.name}</option>`).join('')}</select></label>
        <label>Rarity<select id="art-rarity">${[5, 4, 3].map((r) => `<option value="${r}">${r}★</option>`).join('')}</select></label>
        <label>Main stat<select id="art-mainstat"></select></label>
        <label>Main stat value<input type="number" id="art-mainstat-value" step="0.1"></label>
        <fieldset class="substat-fieldset">
          <legend>Substats (up to 4)</legend>
          ${[0, 1, 2, 3].map((i) => `
            <div class="substat-row">
              <select class="art-substat-type" data-idx="${i}">
                <option value="">— none —</option>
                ${GENSHIN_DATA.substatKeys.map((s) => `<option value="${s}">${GENSHIN_DATA.statLabels[s]}</option>`).join('')}
              </select>
              <input type="number" class="art-substat-value" data-idx="${i}" step="0.1" placeholder="value">
            </div>
          `).join('')}
        </fieldset>
        <button type="submit">Add artifact</button>
      </form>
      <div id="artifact-list"></div>
    </section>
  `;

  const slotSel = document.getElementById('art-slot');
  const mainStatSel = document.getElementById('art-mainstat');
  const mainStatValInput = document.getElementById('art-mainstat-value');

  function populateMainStatOptions() {
    const slotDef = GENSHIN_DATA.artifactSlots.find((s) => s.id === slotSel.value);
    const options = slotDef.fixedMainStat ? [slotDef.fixedMainStat] : slotDef.mainStatOptions;
    mainStatSel.innerHTML = options.map((o) => `<option value="${o}">${GENSHIN_DATA.statLabels[o]}</option>`).join('');
    mainStatSel.disabled = options.length === 1;
    onMainStatChange();
  }
  function onMainStatChange() {
    mainStatValInput.value = GENSHIN_DATA.mainStatMaxValue[mainStatSel.value] || '';
  }
  slotSel.addEventListener('change', populateMainStatOptions);
  mainStatSel.addEventListener('change', onMainStatChange);
  populateMainStatOptions();

  document.querySelectorAll('.art-substat-type').forEach((sel) => {
    sel.addEventListener('change', (e) => {
      const idx = e.target.dataset.idx;
      const valInput = document.querySelector(`.art-substat-value[data-idx="${idx}"]`);
      const stat = e.target.value;
      valInput.value = stat ? (GENSHIN_DATA.substatMaxRoll[stat] || '') : '';
    });
  });

  document.getElementById('add-artifact-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const substats = [];
    document.querySelectorAll('.art-substat-type').forEach((sel) => {
      const idx = sel.dataset.idx;
      const type = sel.value;
      if (!type) return;
      const value = Number(document.querySelector(`.art-substat-value[data-idx="${idx}"]`).value) || 0;
      substats.push({ type, value });
    });
    const artifact = {
      setId: document.getElementById('art-set').value,
      slot: slotSel.value,
      rarity: Number(document.getElementById('art-rarity').value),
      mainStat: mainStatSel.value,
      mainStatValue: Number(mainStatValInput.value) || 0,
      substats,
      reservedFor: null,
    };
    Store.addArtifact(artifact);
    renderArtifactsTab(app);
  });

  renderArtifactList();
}

function renderArtifactList() {
  const container = document.getElementById('artifact-list');
  if (!container) return;
  const artifacts = Store.state.artifacts;
  if (artifacts.length === 0) { container.innerHTML = '<p class="hint">No artifacts added yet.</p>'; return; }
  const ownedChars = Store.ownedCharacters();
  container.innerHTML = `
    <table class="data-table">
      <thead><tr><th>Set</th><th>Slot</th><th>Main</th><th>Substats</th><th>Reserved for</th><th></th></tr></thead>
      <tbody>
        ${artifacts.map((a) => {
          const setName = (GENSHIN_DATA.artifactSets.find((s) => s.id === a.setId) || {}).name || a.setId;
          const slotName = (GENSHIN_DATA.artifactSlots.find((s) => s.id === a.slot) || {}).name || a.slot;
          const subs = (a.substats || []).map((ss) => `${GENSHIN_DATA.statLabels[ss.type]} ${ss.value}`).join(', ');
          return `<tr>
            <td>${escapeHtml(setName)}</td>
            <td>${SLOT_ICON[a.slot] || ''} ${slotName}</td>
            <td>${GENSHIN_DATA.statLabels[a.mainStat]} ${a.mainStatValue}</td>
            <td>${subs || '—'}</td>
            <td>
              <select class="reserve-select" data-id="${a.instanceId}">
                <option value="">— unreserved —</option>
                ${ownedChars.map((c) => `<option value="${c.id}" ${a.reservedFor === c.id ? 'selected' : ''}>${escapeHtml(c.name)}</option>`).join('')}
              </select>
            </td>
            <td><button class="danger-btn" data-id="${a.instanceId}">Remove</button></td>
          </tr>`;
        }).join('')}
      </tbody>
    </table>
  `;
  container.querySelectorAll('.danger-btn').forEach((btn) => {
    btn.addEventListener('click', () => { Store.removeArtifact(btn.dataset.id); renderArtifactList(); });
  });
  container.querySelectorAll('.reserve-select').forEach((sel) => {
    sel.addEventListener('change', (e) => {
      const artifact = Store.state.artifacts.find((a) => a.instanceId === e.target.dataset.id);
      if (artifact) { artifact.reservedFor = e.target.value || null; Store.save(); }
    });
  });
}

// ---------------------------------------------------------- Weapon Optimizer
function renderWeaponOptimizerTab(app) {
  app.innerHTML = `
    <section class="panel">
      <h2>Weapon Optimizer</h2>
      <p class="hint">Finds the best one-to-one assignment of your inventory weapons to your owned characters (matching weapon type), maximizing total stat value across everyone at once — not just picking the top weapon per character independently. A weapon on that character's community best-weapons list (marked ★) always wins over one that isn't; otherwise it falls back to the stat-priority sliders from the Characters tab.</p>
      <button id="compute-wpn-btn">Compute best assignment</button>
      <div id="wpn-opt-result"></div>
    </section>
  `;
  document.getElementById('compute-wpn-btn').addEventListener('click', () => {
    lastWeaponAssignmentResult = computeWeaponAssignment(Store.ownedCharacters(), Store.state.weapons);
    renderWeaponOptResult();
  });
  if (lastWeaponAssignmentResult) renderWeaponOptResult();
}

function renderWeaponOptResult() {
  const container = document.getElementById('wpn-opt-result');
  if (!container || !lastWeaponAssignmentResult) return;
  const { assignments, unassignedCharacters, leftoverWeapons } = lastWeaponAssignmentResult;
  const sorted = assignments.slice().sort((a, b) => b.score - a.score);
  container.innerHTML = `
    <h3>Recommended assignments</h3>
    ${sorted.length ? `<table class="data-table">
      <thead><tr><th>Character</th><th>Weapon</th><th>Refine</th><th>Score</th><th></th></tr></thead>
      <tbody>${sorted.map((a) => `
        <tr>
          <td>${avatarHtml(a.character, 'avatar-sm')} ${escapeHtml(a.character.name)}</td>
          <td>${weaponIconHtml(a.weapon)} ${escapeHtml(a.weapon.name)}${isPreferredWeapon(a.character.id, a.weapon.weaponId) ? ' <span class="pref-star" title="On the community best-weapons list for this character">★</span>' : ''}</td>
          <td>R${a.weapon.refinement}</td>
          <td>${a.score.toFixed(1)}</td>
          <td><button class="save-assign-btn" data-char="${a.character.id}" data-weapon="${a.weapon.instanceId}">Save</button></td>
        </tr>
      `).join('')}</tbody>
    </table>` : '<p class="hint">No matches yet — you need owned characters and weapons of the same type.</p>'}
    ${unassignedCharacters.length ? `<h3>Owned characters with no matching weapon in inventory</h3>
      <p>${unassignedCharacters.map((c) => escapeHtml(c.name)).join(', ')}</p>` : ''}
    ${leftoverWeapons.length ? `<h3>Unused weapons of matching types</h3>
      <p>${leftoverWeapons.map((w) => escapeHtml(w.name)).join(', ')}</p>` : ''}
  `;
  container.querySelectorAll('.save-assign-btn').forEach((btn) => {
    btn.addEventListener('click', () => {
      const weapon = Store.state.weapons.find((w) => w.instanceId === btn.dataset.weapon);
      if (weapon) {
        weapon.assignedTo = btn.dataset.char;
        Store.save();
        btn.textContent = 'Saved ✓';
        btn.disabled = true;
      }
    });
  });
}

// -------------------------------------------------------- Artifact Optimizer
function renderArtifactOptimizerTab(app) {
  const owned = Store.ownedCharacters();
  app.innerHTML = `
    <section class="panel">
      <h2>Artifact Optimizer</h2>
      <p class="hint">Pick a character and see the best build from your artifact inventory — tries no-set, every single 4-piece set you have enough pieces for, and every pair of 2-piece sets, then keeps whichever scores highest for that character's stat priorities. Artifacts reserved for a different character (Artifacts tab) are excluded.</p>
      ${owned.length ? `
        <label>Character
          <select id="art-opt-char">${owned.map((c) => `<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select>
        </label>
        <button id="compute-art-btn">Compute best build</button>
      ` : ''}
      <div id="art-opt-result"></div>
    </section>
  `;
  if (owned.length === 0) {
    document.getElementById('art-opt-result').innerHTML = '<p class="hint">Mark some characters as owned in the Characters tab first.</p>';
    return;
  }
  document.getElementById('compute-art-btn').addEventListener('click', () => {
    const charId = document.getElementById('art-opt-char').value;
    const character = Store.getCharacter(charId);
    const available = Store.state.artifacts.filter((a) => !a.reservedFor || a.reservedFor === charId);
    const result = bestArtifactBuild(character, available);
    renderArtifactOptResult(character, result);
  });
}

function renderArtifactOptResult(character, result) {
  const container = document.getElementById('art-opt-result');
  if (!result) {
    container.innerHTML = '<p class="hint">Not enough artifacts in inventory to fill all 5 slots yet (need at least one available piece per slot).</p>';
    return;
  }
  const { best, runnerUps } = result;
  const rows = ARTIFACT_SLOTS.map((slot) => {
    const a = best.chosen[slot];
    const slotName = (GENSHIN_DATA.artifactSlots.find((s) => s.id === slot) || {}).name || slot;
    const setName = (GENSHIN_DATA.artifactSets.find((s) => s.id === a.setId) || {}).name || a.setId;
    const subs = (a.substats || []).map((ss) => `${GENSHIN_DATA.statLabels[ss.type]} ${ss.value}`).join(', ');
    return `<tr>
      <td>${SLOT_ICON[slot] || ''} ${slotName}</td>
      <td>${escapeHtml(setName)}</td>
      <td>${GENSHIN_DATA.statLabels[a.mainStat]} ${a.mainStatValue}</td>
      <td>${subs || '—'}</td>
    </tr>`;
  }).join('');
  container.innerHTML = `
    <h3>${avatarHtml(character, 'avatar-sm')} Best build for ${escapeHtml(character.name)}</h3>
    <p class="set-bonus-label">${escapeHtml(best.setBonus)} — total score ${best.total.toFixed(1)}</p>
    <table class="data-table">
      <thead><tr><th>Slot</th><th>Set</th><th>Main stat</th><th>Substats</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    ${runnerUps.length ? `<h4>Other options considered</h4>
      <ul>${runnerUps.map((r) => `<li>${escapeHtml(r.setBonus)} — score ${r.total.toFixed(1)}</li>`).join('')}</ul>` : ''}
  `;
}
